library(shiny)
library(lubridate)
library(bslib)

# 1) Define the question sets (paste your full soe_list here)
soe_list <- list(
    anatomy = c(
        "Explain me the course of the corticospinal tract", ###
        "What is the thoracic inlet?",
        "How would you perform an interscalene brachial plexus block?",
        "How would you perform a supraclavicular brachial plexus block?",
        "How would you perform an infraclavicular brachial plexus block?",
        # https://anatomyqa.com/ciliary-ganglion/
        "Explain the anatomy of the oculocardiac reflex",
        "How would you perform an axillary brachial plexus block?",
        "How would you perform a suprascapular nerve block?",
        "What are the diaphragmatic openings and its contents?",
        "Describe the possible route of a sympathic preganglionic fiber",
        "How are splanchnic ganglia innervated?",
        "What are the different types of nerve fibres?",
        "How would you perform a superficial cervical plexus block?",
        "How would you perform a deep cervical plexus block?",
        "How would you perform a transversus abdominis plane (TAP) block?",
        "What types of pain fibres are there?",
        "How would you perform a rectus sheath block?",
        "Tell be about the kidney (ABC)",
        "How would you perform a quadratus lumborum block?",
        "What is the course of blood vessels through the kidneys?", 
        "How would you perform an erector spinae plane block?",
        "How would you perform a paravertebral block?",
        "How would you perform a pectoral nerve block (PECS I and II)?",
        "How would you perform a serratus anterior plane block?",
        "Describe the structure of the sarcomere",
        "How would you perform a fascia iliaca block?",
        "Describe the gate control theory of pain", #
        "What problems can occur with CSF circulation?",
        "How would you perform a femoral nerve block?",
        "Explain the innervation of the muscle spindles and golgi tendon organs",
        "How would you perform an adductor canal block?",
        "How would you perform an obturator nerve block?",
        "How would you perform a sciatic nerve block in the gluteal region?",
        "What are the bounderies of the adductor canal?",
        "What are the contents of the tarsal tunnel?",
        "Explain the mnemonic Tom, Dick And Very Nervous Harry", 
        "Describe the anatomy of the spinal nerve",
        "Draw the fossa poplitea", #
        "Describe the circulation of CSF",
        "What are the borders of the fascia iliaca compartment?",
        "What is pH and why does it matter?",
        "What is the foramen ovale?",
        "Dras the lumbosacral plexus",
        "What is the course of the sciatic nerve?",
        "What is 'power' with regards to a buffer?",
        # https://en.wikipedia.org/wiki/Juxtaglomerular_apparatus
        "Explain the anatomy and function of the jugstaglomerular apparatus",
        "Waht is a Malpighian Body?",
        "Can you describe and draw the glomerulus with the cells involved?",
        "What do you understand by the autonomic nervous system?",
        "How is the nervous system organised?",
        "How is blood flow controlled through capillary beds?",
        "What is the course and innervation of the obturator nerve?",
        "How many nuclei does the vagus nerve have and what is their function?",
        "Tell me about the sympathetic chain",
        "What are the posterior muscles of the foot?",
        # https://www.youtube.com/shorts/i38zHAcCrz8
        "What are the distal branches of the tibial nerve?",
        "Describe the sacroiliacal plexusus",
        "Tell me about the sympathetic nervous system",
        "Tell me about the stellate ganglion, and why it is relevant to anaesthetic practice",
        "What are the subtypes of muscarinic (cholinergic) receptors?",
        "How many nuclei does the vagus nerve have and what is their function?",
        "What is the ductus arteriosus?",
        "Tell me the most important dermtomal landmarks",
        "Which neuron type do you know responsible for motor innervation?", 
        "How is the nervous system organised?",
        "Tell me about the parasympathetic nervous system",
        "Explain the course and innervations of the tibial nerve and its relations to the popliteal fossa/tarsal tunnel"
    ),
    physics_physiology = c(
        "Tell me how oxygen is carried in blood.",
        "What is the structure of haemoglobin (Hb)?",
        "How does foetal Hb differ from adult Hb?",
        "What is 2,3-DPG?",
        "How does the saturation of Hb occur?",
        "What systems in the body act to maintain control of pH?",
        "What is pKa in relation to buffer systems?",
        "What is the oxygen dissociation curve (ODC)?",
        "Can you draw the oxyhaemoglobin dissociation curve and explain what shifts it to the right or to the left?",
        "What is the Bohr effect?", #
        "Tell me about the bicarbonate-carbonic acid buffer",
        "How quickly do differentbuffer systems act?",
        "What determines how effective a buffer is?",
        "How does the kidney handle acid?",
        "What factors increase afterload?",
        "What are the causes of raised intracranial pressure?",
        "What is the isohydric principle?",
        "Calculate the ph for the Carbonic-CO2 buffer system using the Handerson-Hasselbalch equation",
        "How much acid is produced by the body per day?",
        "What effect does temperature have on CMRO2?",
        "What is the Haldane effect?",
        "What is the Monroe-Kellie doctrine?",
        "How much CSF is there in the brain and spinal cord, and how is it produced?",
        "Where does CO2 come from?",
        "What is the CMRO2 value?",
        "Please draw and explain the oxyhemoglobin dissociation curve",
        "What is flow-metabolism coupling?",
        "How does the body detect hypoxia and how does it respond?",
        "Describe the foetal circulation",
        "How does the collecting duct work?",
        "What is streaming?",
        "Explain the Fick law of diffusion formula",
        "What considerations do you need to make regarding heart rate in heart transplant patient?",
        "What are the effects of altitude on the body?",
        "What conditions shift this curve to the right and to the left?",
        "Please draw and explain the pacemaker action potential", 
        "What is oxygen flux?",
        "What role does potassium play and what are normal plasma levels?",
        "Tell me about the blood supply to the kidney",
        "What is the structure of a muscle spindle?",
        "What factors increase afterload?",
        "What is base excess when compared to 'standard' base excess?",
        "What are the causes of hyperkalaemia?",
        "How is CaO2 estimated?",
        "What is the formula for net filtration in the bowman’s capsule?", #
        "What are the causes of hypokalaemia?",
        "How does sodium concentration in the tubular fluid change through the nephron?",
        "How does the liver contribute to buffering?",
        "Can you draw a diagram to demonstrate the pain pathway to the brain?",
        "What is critical DO2?", # 
        "What is the Pasteur point?",
        "Draw the left ventricular pressure volume loop and explain the points",
        "What is the function of capillaries and what features allow them to perform this role?",
        "What is oxygen extraction ratio?",
        "What factors influence stroke volume?", 
        "What are the causes and features of hypomagnesaemia?",
        "What is the function of CSF?",
        "What is base excess when compared to 'standard' base excess?", 
        "Can you tell me the components of the reflex arc?",
        "What are the methods of measuring anaerobic threshold?", 
        "Why we consider the blood-brain barrier when choosing anaesthetic drugs?",
        "What is the role of sodium within the body, and what are the daily requirements?",
        "What factors increase afterload?",
        "What are sinusoidal capillaries?",
        "What happens to the waveform if the compliance of the brain decreases?",
        "What are the different types of data?",
        "What are the different measures of central tendency?", ###
        "How does fluid move between intra and extracellular fluid?",
        "Describe the nephron and where do the diuretic drugs work?",
        "How does oxygen content in the blood change with altitude?",
        "Can you tell me the differences between the different types of muscle?",
        "Can you describe the different types of aquaporin?",
        "How is 2,3-DPG produced and what does it do?",
        "What factors increase 2,3-DPG production?",
        "What are the requirenments for a patient who is nil by mouth (NBM) before surgery?",
        "What is the alveolar gas equation?",
        "What assumptions are required for the alveolar gas equation?",
        "How are muscle spindles innervated?", 
        "How can you demonstrate work done and stroke volume on this graph?",
        "Tell me about GFR",
        "What is the golgi tendon organ and what does it do?",
        "How does PaCO2 affect PAO2?",
        "How do you treat hypermagnesaemia?",
        "How much sodium is lost by the body per day?",
        "What happens in muscular dystrophy?",
        "What are the causes and features of hypermagnesaemia?",
        "What does isotonic mean?",
        "What are the necessary components of an electrocardiogram?",
        "What tells alveolar gas equation about the PiO2 and PAO2 relationship?",
        "Can you explain how an atrioventricular nodal re-entrant tachycardia works?",
        "How does CO2 affect ventilation?",
        "How is the alveolar gas equation affected by altitude?",
        "What are the clinical features of lower and upper motor neurone injury?",
        "PaO2 in an aircraft with a cabin pressure of 80kPa?",
        "How does the kidney handle acid?",
        "What is base excess when compared to 'standard' base excess?",
        "How does PAO2 affect minute ventilation?",
        "How does minute ventilation affect PAO2?",
        "What are the causes and features of hypomagnesaemia?",
        "What factors increase afterload?",
        "How does the respiratory quotient change in COPD?",
        "Can you tell me about the structure and function of the muscle spindle?",
        "Can you draw a diagram to demonstrate the pain pathway to the brain?",
        "What is shunt and what categories do you know?",
        "What is the Henderson-Hasselbalch equation?",
        "What effect does shunt have?",
        #  https://www.youtube.com/watch?v=2CzQoFtlg3w
        "Draw and explain the countercurrent multiplier mechanism",
        "What is the role of the vasa recta and peritubular capillaries?",
        "What happens if you increase the FiO2?",
        "How is CaO2 estimated?",
        "What is spirometry?",
        "Please draw a normal vitalograph spirometry trace for a single exhaled breath",
        "Draw a spirometry trace of normal tidal volume breathing, and then a maximal inspiratory and expiratory breath",
        "What volumes cannot be measured using spirometry?",
        "What is compliance?",
        "What is hysteresis?",
        "Please draw the following Flow-Volume Curves",
        "What is ventricular elastance and show it on a LV PV Loop?",
        "What are the systemic effects of magnesium?",
        # https://www.youtube.com/watch?v=2CzQoFtlg3w
        "Draw and explain the countercurrent multiplier mechanism",
        "How does the kidney handle acid?",
        "What factors influence stroke volume?",
        "What is the Bell–Magendie law?",
        "What is Transfer factor?",
        "Where in the body is magnesium found and what is its normal concentration?",
        "Tell me about renal blood flow autoregulation by drawing a graph",
        "How does the kidney handle acid?",
        "How can dead space be calculated?",
        "What does magnesium do?",
        #https://www.youtube.com/watch?v=2CzQoFtlg3w
        "Why are there two countercurrent mechanism?",
        "Please discuss the production, circulation, and contents of cerebrospinal fluid (CSF).",
        "How would the body react to a bolus of acid?",
        "What functions does the CSF fulfil?", ##
        "Explain the mechanism of CSF’s ability to protect the brain from ischaemia (The Monro–Kellie doctrine)", ###
        "What is cerebral perfusion pressure?",
        "How does ventilation affect CO2?",
        "What are the effects of PaCO2 and PaO2 on cerebral blood flow (graphs)?",
        "How does CO2 affect intracranial pressure?",
        "What is the blood-brain barrier?",
        "What is normal cerebral blood flow, and what factors affect it?",
        "What effect would an increase in preload have on LV PV loop?",
        "Why does the anaesthetist have to consider the blood-brain barrier when choosing anaesthetic drugs?",
        "What are the circumventricular organs and what is their function?",
        "How does CSF differ to plasma?",
        "How can you measure dead space?",
        "What are the main functions of the hypothalamus?",
        "Please describe the relationship between ventilation and perfusion in different parts of the lungs.",
        "Can you draw and explain the left ventricular volume/time graph?",
        "Tell me about the haemoglobin buffer system",
        "Should we hyperventilate patients with high intracranial pressure?",
        "What is a pulmonary shunt and under which clinical conditions does shunt occur?",
        "What effect does increasing venous filling have on venous return and cardiac output?",
        "What is dead space and what types of dead space are there?",
        "Tell me about the factors influencing the diffusion of gases between pulmonary capillaries and alveoli",
        "What is the resting membrane potential?", 
        "Tell me about plasma proteins and phosphate as buffering systems", # 
        "Can you draw and explain the function of the loop of Henle?",
        "What is the Donan effect?", #
        "How does skeletal muscle contract?",
        "Draw a graph to show how renal excretion of glucose changes with plasma concentration",
        "Why does carbon dioxide equilibrate faster than oxygen between the alveoli and the pulmonary capillaries?",
        "How can the body compensate for the increased ventilation and perfusion during physical activity?",
        "What is the equation for venous return?",
        "How can nociceptive pain be classified?",
        "Tell me about the production, composition, circulation and reabsorbtion of CSF",
        "What is hypoxic pulmonary vasoconstriction (HPV)?",
        "Please describe the physiological functions of the kidneys.",
        "What is neuropathic pain?",
        "Please describe the three mechanisms involved in urine production",
        "What is glomerular filtration rate?",
        "What is renal clearance?",
        "What is chronic pain?",
        "How can it be measured?",
        "What is autoregulation of renal blood flow?", 
        "What do nociceptors detect?",
        "Describe the sacroiliacal plexus",
        "What would it look like for a failing ventricle?",
        "What is heterometric autoregulation?",
        "Can you explain how an atrioventricular nodal re-entrant tachycardia works?",
        "What is the equation for venous return?",
        "What effect does reducing venous resistance have on venous return and cardiac output?",
        "What effect does increasing venous filling have on venous return and cardiac output?",
        "How does the respiratory cycle affect preload?",
        "Can you explain the Frank-Starling mechanism in relation to the heart?",
        "What does the LVEDP-SV graph look like in heart failure?",
        "What pressure values are normal for each chamber of the heart?",
        "What is the Fick principle?",
        "How can the Fick principle be used to calculate Cardiac output?",
        "Can you draw and explain the MAP formula?",
        "Tell me about pressure is the pressure driving flow to the coronary arteries",
        "What are the mechanisms?",
        "How does the kidney contribute to the regulation of the water balance in the body?",
        "Please describe the renin-angiotensin-aldosterone system (RAAS).",
        "What effect does reducing venous resistance have on venous return and cardiac output?", 
        "How is calcium stored in the body?",
        "Is calcium mainly an intra- or an extracellular ion?",
        "Describe the membrane potential",
        "What is the normal plasma level of calcium?",
        "How is calcium represented in plasma?",
        "What are the functions of calcium in the body?",
        "How is the metabolism of calcium regulated in the body?",
        "What is the Gibbs-Donnan effect?",
        "Describe the davenport normogram and draw it",
        "Tell me about the role of parathyroid hormone in calcium homeostasis.",
        "What is the role of calcitonin in calcium regulation?",
        "How is Vitamin D involved in calcium regulation?",
        "Outline the anatomy of the larynx.",
        "Name the laryngeal cartilages.",
        "What is the Nernst equation?",
        "Describe the anatomy of the thyroid cartilage.",
        "Outline the anatomy of the cricoid cartilage.",
        "Describe the neuromuscular junction",
        "Outline the anatomy of the epiglottis.",
        "What are the arytenoid cartilages?",
        "Briefly describe the anatomy of the cuneiform and corniculate cartilages.",
        "What are the types of hypoxia?",
        "What is the Goldman equation?",
        "Explain the concept for the volume of distribution (Units)",
        "Where does the autonomic system innervate the heart?",
        "Can you plot arterial and venous points on the O2 dissociation curve for various types of hypoxia?",
        "What factors cause a reduction in transfer factor (TLCO)?",
        "Can you draw the pressure-volume loop for the lung as a single unit?",
        "How is the Henderson–Hasselbalch equation derived and what does it tell us?",
        "What are Starling forces?",
        "What different types of ribs are there?",
        "How does pulmonary vascular resistance change with lung volume (graph)?",
        "Describe the anatomy of the first rib.",
        "Tell me what you know about the body fluid compartments and plasma composition",
        "What is the clinical relevance of a first rib fracture?",
        "What are the boundaries of the thoracic inlet?",
        "What ECG changes are seen with hypocalcaemia?",
        "What is the cardiac cycle?",
        "What ECG changes are seen with hypokalaemia and hyperkalaeia?",
        "Draw a V/Q graph",
        "How would you calculate the maintenance fluid requirement for a 90kg patient?",
        "What structures pass through the thoracic inlet?",
        "What is dead space?", #
        "Describe the course of the subclavian arteries.",
        "Describe the anatomy of the subclavian veins.",
        "Why do children frequently develop bradycardia in response to an insult?",
        "What is the ideal location for the tip of a central venous catheter?",
        "What is the cardiac cycle?",
        "Outline the anatomy of the diaphragm.",
        "Describe the muscular attachments of the diaphragm.",
        "What is the Haldane Effect?",
        "What’s lung resistance?",
        "What do you understand by the term ‘time constant’?",
        "How is CO2 removed from the body (draw a graph)?",
        "Tell me about cerebral autoregulation (graph)",
        "How can you measure dead space?",
        "What are the main openings in the diaphragm?",
        "How is CO2 carried around the body?",
        "What is the innervation of the diaphragm?",
        "How is pulmonary vascular resistance calculated?",
        "Explain the units of PVR (dynes * s * cm^-5) and how it is calculated",
        " What factors affect pulmonary vascular resistance?",
        "Can you draw the CO2 Dissociation Curve?",
        "What is a diaphragmatic hernia?", #
        "Can you explain the graphs in relation to a pulmonary artery catheter?",
        "Briefly outline the different types of diaphragmatic herniae.",
        "How is CO2 removed from the body (draw a graph)?",
        "What is the conversion factor for glucose mmols(L to mg/dL?",
        "What is the cardiac cycle?",
        "Describe the general structure of the abdominal wall.",
        "What muscles are found in the anterolateral abdominal wall?",
        "Name the muscles of the posterior abdominal wall.",
        "Outline the nerve supply to the anterolateral abdominal wall.",
        "What is the difference between static and dynamic compliance?",
        "What is the thoracolumbar fascia?",
        "Can you tell me about the structure and function of the muscle spindle?",
        "What is CVP and why do we use it?",
        "Where does the autonomic system innervate the heart?",
        "Tell me about the anatomy of the lumbar plexus.",
        "Describe the anatomy of the femoral nerve.",
        # https://www.tiktok.com/@anaestheasier/video/7436091968536595744
        "Explain the Bohr equation?", 
        "What structures are innervated by the femoral nerve?",
        "What are the borders and contents of the femoral triangle?",
        "What is the femoral sheath?",
        "What is the adductor canal?",
        "Outline the course of the obturator nerve",
        "What is the lumbosacral trunk?"
    ),
    pharmacology_clinical_measurements = c(
        "What different groups of local anaesthetics do you know?",
        "Can you draw the CVP waveform and explain it??",
        "Describe the principle of the Vacuum insulator evaporator?",
        "Can you tell me how local anaesthetics work?",
        "Tell me how local anaesthetics vary in pharmacological and clinical properties and explain why?",
        "What does protein binding determine?",
        "What would the graph look like in Aortic Stenosis?",
        "What is the significance of the pKa?",
        "How are the augmented and wilson leads derived?",
        "Tell me more about lipid solubility.",
        "What are the different types of lactic acidosis?",
        "What do you know about local anaesthetic metabolism?",
        "What can you tell me about additives to local anaesthetics that influence their action?",
        "What is an Osmole and how is it measured?",
        "Tell me about the different routes of administration of local anaesthetics",
        "What do you understand by the term ‘differential block’?",
        "Explain the concept of efficacy and potency.",
        "What do you understand by the term ‘agonist’?",
        "Can you explain the graphs in relation to a pulmonary artery catheter?",
        "What would it look like for a failing ventricle?",
        "How does sepsis cause a lactic acidosis?",
        "What is an ‘antagonist’?",
        "You have mentioned two terms: ‘affinity’ and ‘intrinsic activity’. Tell me more about them",
        "What is the difference between an agonist and an antagonist if they both bind to the same receptor?",
        "What types of agonists are you aware of?",
        "Give me some clinical examples of full and partial agonists?",
        "What is the difference between full and partial agonists?",
        "What would it look like for a failing ventricle?",
        "What is heterometric autoregulation?",
        "What is an Osmole?",
        "What are the causes of pleural effusions?",
        "Explain the concept of efficacy and potency.",
        "What is an inverse agonist?",
        "How can we graphically compare the efficacy of different agonists?",
        "What is so useful about this plot that could be used to compare two different agonists?",
        "Tell me what the dose/response curve looks like for a partial agonist.",
        "What kind of antagonists are there?", #
        "What is osmotic pressure and how is it calculated?",
        "What do you understand by the term competitive antagonist?",
        "Can the action of competitive antagonists be reversed?",
        "How is pleural fluid produced and what role does it serve?",
        "Tell me about non-competitive antagonists and give an example?", #
        "How do they produce their effects?",
        "Why do tachyarrhythmias occur?",
        "How is glucose handled by the kidney?", #
        "What are the irreversible antagonists?",
        "What is the difference between an inverse agonist and a competitive antagonist?",
        "How can general anaesthesia be administered?",
        # https://www.youtube.com/watch?v=2eiLaFlTfKc
        "Can you describe and draw the glomerulus with the cells involved?",
        "When would you prefer an inhalational versus an intravenous induction?",
        "What are the features of an ideal inhalational anaesthetic agent?",
        "What is ‘saturated vapour pressure’ and how is it clinically relevant?",
        "How is chloride reabsorbed in the PCT?",
        "Tell me about the cardiac axis",
        "What are the different types of lactic acidosis?",
        "What is base excess when compared to 'standard' base excess?",
        "How do you define the ‘blood:gas partition coefficient’ and how is it clinically relevant?",
        "What is the ‘oil:gas partition coefficient’ and how is it clinically relevant?",
        "jlkWhat do you understand by ‘MAC’ and how is it clinically relevant?",
        "What are the causes of metabolic acidosis?",
        "Please describe what happens during a Valsalva manoeuvre",
        "What factors can increase or decrease MAC?",
        "Which inhalational anaesthetic agents are currently in clinical use?",
        "Which two inhalational anaesthetic agents do you use most frequently?",
        "Why might a patient become bradycardic?",
        "Compare and contrast the properties of these two agents.",
        "What are the types of refractory period?",
        "What is nitrous oxide?",
        "What are the advantages and disadvantages of using nitrous oxide?",
        # https://cvpharmacology.com/
        "Tell me about amiodaron",
        "Tell me about lidocaine",
        "How can general anaesthesia be administered?",
        "What are the properties of the ideal intravenous induction agent?",
        "Which central receptors do the intravenous induction agents act on?",
        "Which intravenous induction agent do you use most often?",
        "Why is propofol your preferred option?",
        "How can filtered substances be reabsorbed in the proximal tubule?",
        "What are the disadvantages of using propofol as an induction agent?",
        "Can you compare and contrast propofol and thiopental as induction agents?",
        "What are the advantages and disadvantages of etomidate as an induction agent?",
        "What is the difference between oncotic and osmotic pressure?",
        "What are the advantages and disadvantages of ketamine as an induction agent?",
        "What other intravenous agents can be used to induce general anaesthesia?",
        "What are the causes of metabolic acidosis?",
        "What is the osmolar gap?",
        "Draw the formula for pyruvate to lactate conversion",
        "What do you understand by the term ‘muscle relaxant’?",
        "What types of muscle relaxants are you aware of?",
        "Tell me about depolarizing muscle relaxants first.",
        "What are the different types of nerve fibres?",
        "What is anion gap?",
        "Describe the side effects of succinylcholine.",
        "Classify the non-depolarizing muscle relaxants.",
        "What are ECG ‘leads’?",
        "How is intraocular fluid produced?",
        "What is compliance?",
        "What is lymph and what does it do?",
        "What are osmoreceptors?",
        "Describe the pharmacology of your preferred muscle relaxant.",
        "Which drugs are used to reverse the action of muscle relaxants?",
        "How can the effect of muscle relaxants be monitored?",
        "How is water distributed throughout the body?",
        "What can potentiate or prolong the effects of muscle relaxants?",
        "What are the indications for using muscle relaxants in anaesthetic practice?",
        "What are the problems with using muscle relaxants in anaesthetic practice?",
        "How does the pulse oximeter work?",
        "Which two particular wavelengths are used and why?",
        "What happens to the electrical signal as it passes from patient to monitor?",
        "What do you understand by ‘isobestic point’ and why is it useful?",
        "Draw a graph representing the different light absorption for deoxygenated and oxygenated haemoglobins.",
        "What is the Beer–Lambert law and what is the importance of it for pulse oximetry?",
        "Draw the formula for pyruvate to lactate conversion",
        "What are sources of error, limitations and problems in interpreting thepulse oxymetry and Beer-Lambert Law?",
        "Can you put COHb) and MetHb light absorption on a graph to demonstrate their absorption characteristics?",
        "What are the methods available for measuring arterial blood pressure?",
        "Tell me about the different non-invasive methods first.",
        "What are the key components of non-automatic intermittent non-invasive methods (NIMs)?",
        "What methods are used to determine flow at systolic and diastolic pressures using NIMs?",
        "What is the automatic, intermittent non-invasive blood pressure measurement method?",
        "Can you explain the graphs in relation to a pulmonary artery catheter?",
        "What is anion gap?",
        "Tell me about currently available continuous non-invasive blood pressure measurement methods.",
        "What are the components of an invasive arterial blood pressure measurement system?",
        "What changes occur after birth?",
        "What effect do anaesthetic agents have on CMRO2 (graph)?",
        "What is the function of a transducer, and how does it work in the system?",
        "What are the sources of error associated with arterial blood pressure measurement?",
        "How is resonance important for causing errors in blood pressure measurement?", #
        "Tell me how damping affects the accuracy of blood pressure measurement.",
        "What happens in the proximal convoluted tubule?",
        "Can you draw the CVP waveform and explain it?",
        "What methods are available to measure gas concentration in a mixture of gases?",
        "Where does the autonomic system innervate the heart?",
        "Explain to me the principle behind the paramagnetic analyser",
        "How is sodium reabsorbed in the PCT?",
        "What is the theoretical principle of infrared capnometry?",
        "What do you understand by the Beer–Lambert law?",
        "What is pulmonary capillary wedge pressure and why is it of interest?",
        "Please draw and label a typical capnography trace seen in a spontaneously breathing patient.",
        "Could you draw a capnography trace representing low cardiac output, oesophageal intubation, and malignant hyperpyrexia?",
        "What types of capnograph do you know about and what are their advantages and disadvantages?",
        "What are the different types of nerve fibres?",
        "What is the principle behind computed tomography (CT)?",
        "What are the components of the CT scanner?",
        "What do you understand by the term computed axial tomography (CAT)?",
        "What is Einthoven’s law?",
        "How is it different from helical scanning?",
        "What is the structure of the BBB?",
        "How can CT imaging be enhanced?",
        "What is the mechanism through which enhancement of the CT image occurs?",
        "Explain how the magnetic resonance imaging (MRI) scanner generates a signal",
        "What are the components of an MRI scanner?",
        "Which aspects of the cardiac AP do each class of antiarrhythmic agent act on?",
        "What are the problems associated with providing anaesthesia for MRI investigations?",
        "What methods are available for monitoring muscle relaxation perioperatively?",
        "What are the main patterns of nerve stimulation used clinically?",
        "What are the indications for using the single twitch method?",
        "Describe the characteristics of a train-of-four stimulation.",
        "What is anion gap?",
        "What do you understand by the train-of-four ratio?",
        "What is the main clinical application of the train-of-four ratio?",
        "What are ECG ‘leads’?",
        "How is double burst stimulation different from train-of-four stimulation?",
        "What is tetanic stimulation?",
        # https://clinicalview.gehealthcare.com/sites/default/files/styles/paragraph_scaled_picture_medium/public/Annotation%202022-05-04%20111901_0.png.webp?itok=p8xfmUAk
        "What do you understand by post-tetanic count and effect on reversal or TOF return??" ##
    ),
    clinical_anaesthesia = c(
        # Patient, Pathology, anesthetic and surgical conserns
        "What framework can be used to formulate major anesthetic conserns for the perioperative Period?",
        # history, functional capacity, investigations, examinations 
        "What framework can be used for evaluating the severity of an underlying preoperative condition?",
        "How is double burst stimulation different from train-of-four stimulation?",
        "What is tetanic stimulation?",
        "How would you perform an RSI induction?",
        "What is the management of AKI?",
        "What are the types of RRT?",
        "What ECG changes are seen in hypothermia?",
        "How is AKI diagnosed?",
        "What is dialysis?",
        "What are the disadvantages of CRRT compared to intermittent?",
        "What are the indications for RRT?",
        "What is acute kidney injury?",
        "Which toxins can be removed by the RRT?",
        "How would you induce a patient using a propofol sparing technique?", # 
        "Which antibiotic is indicated for contaminated traumatic injuries?",
        "Explain me the Brown-Sequard syndrome",
        "Wher do the diurhetic drugs work in the nephron?",
        "How can intracranial pressure be monitored?",
        # structural, functional and haemodynamic assessment
        "What framework can you use for evaluating the TTE/TEE examination?",
        "Explain how antiarrhythmic agents are classified", ##
        "What are the indications specifically for CRRT?",
        "What are responses to a Valsalva manouvre seen in neuropathy and heart failure?",
        "What is ultrafiltration?",
        "What conditions affect DLCO and KCO?", 
        "Which blocks should be performed for Total Knee Arthroplasty (TKA)?",
        "How can you work out ejection fraction and how much is it?", 
        "Tell me the KDOGO criteria for acute kidney injury",
        "What are the GURDs creteria?",
        "What are the complications associated with RRT?",
        "What features of CRRT need to be prescribed?",
        "What is the difference between Duchenne and Becker muscular dystrophy?",
        "Describe the Vaughan Williams Classiification", 
        "What is cardiac tamponade and why does it occur?",
        "What are the clinical features of raised intracranial pressure?",
        "How is AKI diagnosed?",
        "What are the management options for raised intracranial pressure?",
        "What is the effect of hypokalaemia and what is a symptom of it?",
        "What do you understand by post-tetanic count and effect on reversal or TOF return?", ##
        "What are the different classes of chemotherapeutic agents?",
        "How is AKI diagnosed?",
        "What are the causes for hypocalcaemia?",
        "What factors affect pulmonary vascular resistance?",    
        "What is the equation for pulmonary vascular resistance?", # 
        "How does SVR relate to blood pressure?",
        "What are the complication of chemotherapeutic agents on the different organs?"
        
    )
)


ui <- fluidPage(
    theme = bs_theme(
        version = 5,
        bootswatch = "cyborg"   # other good ones: "cyborg", "slate", "superhero"
    ),
    titlePanel("SOE Question Trainer"),
    sidebarLayout(
        sidebarPanel(
            actionButton("next_btn", "Next question"),
            actionButton("quit", "Reset session"),
            hr(),
            checkboxInput("random_section", "Random section each time", FALSE),
            # helpText("Click 'Next question' to advance.")
        ),
        mainPanel(
            h3(textOutput("days_left")),
            h4(textOutput("section")),
            tags$pre(textOutput("question"))
        )
    )
)

server <- function(input, output, session) {
    
    future_date <- ymd("2026-06-27")
    
    # State: current section index + current question text
    state <- reactiveValues(
        i = 1,
        section = names(soe_list)[1],
        question = ""
    )
    
    # Helper to compute days left
    days_left <- reactive({
        now <- today()
        as.integer(time_length(future_date - now, unit = "days"))
    })
    
    # Function that picks a new question based on current state
    pick_question <- function() {
        if (isTRUE(input$random_section)) {
            state$section <- sample(names(soe_list), 1)
            state$i <- match(state$section, names(soe_list))
        } else {
            state$section <- names(soe_list)[state$i]
        }
        
        current_set <- soe_list[[state$section]]
        state$question <- sample(current_set, 1)
    }
    
    # Initial question
    observeEvent(TRUE, {
        pick_question()
    }, once = TRUE)
    
    # Next button
    observeEvent(input$next_btn, {
        if (!isTRUE(input$random_section)) {
            state$i <- state$i + 1
            if (state$i > length(soe_list)) state$i <- 1
        }
        pick_question()
    })
    
    # Reset button
    observeEvent(input$quit, {
        state$i <- 1
        state$section <- names(soe_list)[1]
        pick_question()
    })
    
    # Outputs
    output$days_left <- renderText({
        paste0("Days left: ", days_left())
    })
    
    output$section <- renderText({
        paste0("Section: ", state$section)
    })
    
    output$question <- renderText({
        state$question
    })
}

shinyApp(ui, server)