```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(tidyverse)
library(lubridate)
library(scales)
# theme_set(theme_minimal())
```

```{r}
movie_profit_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-23/movie_profit.csv")
```

```{r}
movie_profit <- movie_profit_raw %>% 
    select(-X1) %>% 
    # because parse_date_time worked as.Date is a cheat around the error from parse_date
    mutate(release_date = as.Date(parse_date_time(release_date, "%m!/%d/%Y")),
           distributor = fct_lump(distributor, n = 6)) %>%
    mutate(decade = 10 * floor(year(release_date) / 10)) %>% 
    distinct(movie, release_date, .keep_all = TRUE) %>% 
    filter(worldwide_gross > 0)
```



```{r}
movie_profit %>% 
    filter(distributor != "NA") %>% 
    mutate(distributor = fct_reorder(distributor, production_budget)) %>% 
    ggplot(aes(distributor, production_budget)) +
    geom_boxplot() +
    # anytime you see money, put it on a log scale
    # this will create a lognormal distribution 
    scale_y_log10(labels = dollar_format()) +
    coord_flip()
```


### What genres make the most money

```{r}
movie_profit %>% 
    mutate(genre = fct_reorder(genre, production_budget)) %>% 
    filter(!is.na(distributor)) %>% 
    ggplot(aes(genre, production_budget)) +
    geom_boxplot() +
    # anytime you see money, put it on a log scale
    # this will create a lognormal distribution 
    scale_y_log10(labels = dollar_format()) +
    coord_flip() +
    facet_wrap(~ distributor)
```

28:25 What genres have the biggest payoffs (worldwide gross to production budget ratio) ?

```{r}
# distribution on a log scale of profit ratios
movie_profit %>% 
    mutate(profit_ratio = worldwide_gross / production_budget) %>%
    ggplot(aes(profit_ratio)) +
    geom_histogram(bins = 60) +
    scale_x_log10()

# distribution on a log scale of profit ration separated by genres
movie_profit %>% 
    mutate(profit_ratio = worldwide_gross / production_budget) %>%
    ggplot(aes(genre, profit_ratio)) +
    geom_boxplot() +
    scale_y_log10() +
    coord_flip()

# barplot of median profit ratios in different genres
movie_profit %>% 
    mutate(profit_ratio = worldwide_gross / production_budget) %>%
    group_by(genre) %>% 
    summarise(median_profit_ratio = median(profit_ratio)) %>% 
    ggplot(aes(genre, median_profit_ratio)) +
    geom_col() +
    coord_flip()


```



What are typical budgets over time

```{r}
movie_profit %>% 
    group_by(decade) %>% 
    summarise_at(vars(production_budget:worldwide_gross), median, na.rm = TRUE) %>% 
    gather(metric, value, -decade) %>% 
    ggplot(aes(decade, value, color = metric)) +
    geom_line() +
    scale_y_continuous(labels = dollar_format())
```

