---
title: "R_downloads"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(tidytuesdayR)
library(countrycode)
theme_set(theme_light())

# https://thebioengineer.github.io/tidytuesdayR/
r_downloads_year <- tt_load(2018, week=31)
r_downloads_year <- r_downloads_year$r_downloads_year

r_downloads_year <- r_downloads_year %>% 
    mutate(country_name = countrycode(country, "iso2c", "country.name"))
```

```{r}
# counting downloads over time
r_downloads_year %>% 
    count(week = floor_date(date, "week")) %>% 
    # droping incomplete weeks
    dplyr::filter(week > min(week)) %>% 
    ggplot(aes(week, n)) +
    geom_line() +
    expand_limits(y = 0) +
    labs(x = "# of R downloads per week")
```

```{r}
r_downloads_year %>% 
    count(country_name = fct_lump(country_name, 8),
          week = floor_date(date, "week")) %>% 
    dplyr::filter(week > min(week)) %>% 
    ggplot(aes(week, n, color = country_name)) +
    geom_line()
```

### Taking a look at IP adresses
```{r}
r_downloads_year %>% 
    count(ip_id, sort = T)
```

# Time between installations
 
```{r}
r_downloads_year %>% 
    mutate(datetime = as.POSIXlt(date) + time) %>% 
    arrange(datetime) %>% 
    group_by(ip_id) %>% 
    mutate(gap = datetime - lag(datetime)) %>% 
    dplyr::filter(!is.na(gap))
    
```

```{r}
# library(lubridate)
# library(countrycode)

r_downloads_year %>% 
    count(date) %>% 
    # label = TRUE will assign the weekdays instead of integers
    group_by(weekday = wday(date, label = TRUE)) %>% 
    summarise(average = mean(n)) %>% 
    ggplot(aes(weekday, average)) +
    # group will connect the dots
    geom_line(group = 1) +
    expand_limits(y = 0)
```

What time of day were people installing R?

```{r}
r_downloads_year %>% 
    mutate(country = countrycode(country, "iso2c", "country.name")) %>% 
    dplyr::filter(!is.na(country)) %>% 
    count(hour = hour(time),
          country = fct_lump(country, 8)) %>%
    ggplot(aes(hour, n)) +
    geom_line() +
    expand_limits(y = 0) +
    facet_wrap(~country, scales = "free_y")
```

```{r}
r_downloads_year %>% 
    count(contry = fct_lump(country, 2),
          week = floor_date(date, "week")) %>% 
    ggplot(aes(week, n)) +
    geom_line() +
    facet_wrap(~os)
```


```{r}
r_downloads_year %>% 
    count(country = countrycode(country, "iso2c", "country.name"), sort = TRUE) %>% 
    mutate(country = fct_reorder(country, n)) %>% 
    dplyr::filter(!is.na(country)) %>% 
    head(13) %>% 
    ggplot(aes(country, n)) +
    geom_col() +
    coord_flip()
    
```


```{r}
r_downloads_year %>% 
    mutate(version = fct_lump(version, 7)) %>% 
    count(date, version) %>% 
    ggplot(aes(date, n, color = version)) +
    geom_line()
```

```{r}
r_downloads_year %>% 
    count(version, sort = TRUE) %>% 
    print(n = 100)

r_downloads_year %>% 
    mutate(version = fct_lump(version, 8)) %>% 
    count(version, sort = TRUE)
```

