```{r}
# imap kj <Esc>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```

# Importing the data
```{r echo = FALSE}
recent_grads <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/college-majors/recent-grads.csv")

# modified and processed version of the dataset
major_processed <- recent_grads |> 
    arrange(desc(Median)) |> 
    mutate(Major = str_to_title(Major),
           Major = fct_reorder(Major, Median))
```

```{r}
major_processed |> 
    group_by(Major_category) |> 
    summarise(Median = median(Median)) |> 
    mutate(Major_category = fct_reorder(Major_category, Median)) |> 
    ggplot(aes(Major_category, Median)) +
    geom_col() +
    coord_flip()
```

Most common major categories

```{r}
major_processed |> 
    count(Major_category, wt = Total, sort = TRUE) |>
    mutate(Major_category = fct_reorder(Major_category, n)) |>
    ggplot(aes(Major_category, n, fill = Major_category)) +
    geom_col() +
    coord_flip() +
    labs(x = "",
         y = "Number of total graduates") +
    theme(legend.position = "none")

major_processed |> 
    group_by(Major_category) |> 
    summarise(n = sum(Total)) |> 
    arrange(desc(n))
```

```{r 34:00}
major_processed |> 
    mutate(Major = fct_reorder(Major, Total)) |>
    arrange(desc(Total)) |> 
    head(20) |> 
    ggplot(aes(Major, Total, fill = Major_category)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = comma_format()) +
    labs(x = "",
         y = "Total # of graduates") +
    theme(legend.position = "none")
```

### 36:00 Gender and typical earning
```{r}
major_processed |> 
    arrange(desc(Total)) |> 
    head(20) |> 
    mutate(Major = fct_reorder(Major, Total)) |> 
    gather(Gender, Number, Men, Women) |> 
    select(Major, Gender, Number) |> 
    ggplot(aes(Major, Number, fill = Gender)) +
    geom_col() +
    scale_y_continuous(labels = comma_format()) +
    coord_flip()
```


39:00 Most shifted proportions
```{r}
major_processed |> 
    group_by(Major_category) |> 
    summarise_at(vars(Total, Men, Women), sum, na.rm = TRUE) |> 
    mutate(ShareWomen = Women / Total) |> 
    arrange(desc(ShareWomen))
```

43:00 Weighting medians and summarise instead of summarise_at
```{r}
# using just summarise
major_processed |> 
    dplyr::filter(!is.na(Total)) |> 
    group_by(Major_category) |> 
    # summary_at only for a single method not different methods
    summarise(Men = sum(Men), 
              Women = sum(Women),
              Total = sum(Total),
              # weighting the medain by sample size?
              # medians can also be affected by high variation ones ...
              # high sample size will get more weights
              MedianSalaryWeighted = sum(Median * Sample_size / sum(Sample_size))) |>  
    mutate(ShareWomen = Women / Total) |> 
    arrange(desc(ShareWomen))
```


