```{r}
library(tidyverse)
library(lubridate)
library(scales)

theme_set(theme_light())
```

```{r}
# 7:20 change to raw 
movie_profit_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-23/movie_profit.csv")

movie_profit <- movie_profit_raw %>%   
    select(-"...1") %>% 
    mutate(release_date = as.Date(parse_date_time(release_date, "%m!/%d/%Y")),
           # six most common distributors and other
           distributor = fct_lump(distributor, n = 6)) %>% 
    dplyr::filter(release_date < "2018-01-01") %>% 
    # reversing order of rows
    arrange(desc(row_number())) %>% 
    distinct(movie, release_date, .keep_all = TRUE) %>% 
    mutate(decade = 10 * floor(year(release_date) / 10)) %>%  # 19:19
    filter(worldwide_gross > 0)
    
```

```{r}
movie_profit %>% 
    ggplot(aes(production_budget)) +
    geom_histogram() +
    scale_x_continuous(labels = dollar_format())
    
# less observations comapered to the video
movie_profit %>% 
    ggplot(aes(production_budget)) +
    geom_histogram() +
    scale_x_log10(labels = dollar_format())

# 17:00 production budget based on distributor
movie_profit %>% 
    ggplot(aes(distributor, production_budget)) +
    geom_boxplot() +
    scale_y_log10(labels = dollar_format()) +
    coord_flip()

```

18:00 Boxplot facets: What genres make the most money

```{r}
movie_profit %>% 
    mutate(genre = fct_reorder(genre, production_budget)) %>% 
    filter(!is.na(distributor)) %>% 
    ggplot(aes(genre, production_budget)) +
    geom_boxplot() +
    scale_y_log10(labels = dollar_format()) +
    coord_flip() +
    # wow, it is possible to use facets after ggplot call
    facet_wrap(~ distributor)
```

22:00 Line graph: What are typical bugdets over time

```{r}
movie_profit %>% 
    # mutate(decade = 10 * floor(year(release_date) / 10)) %>% 
    group_by(decade) %>% 
    summarise_at(vars(production_budget:worldwide_gross), median, na.rm = TRUE) %>% 
    gather(metric, value, -decade) %>% 
    ggplot(aes(decade, value, color = metric)) +
    geom_line() +
    scale_y_continuous(labels = dollar_format())
```

27:00 Boxplot facets: What genres make the most worldwide gross

```{r}
movie_profit %>% 
    mutate(genre = fct_reorder(genre, worldwide_gross)) %>% 
    filter(!is.na(distributor)) %>% 
    ggplot(aes(genre, worldwide_gross)) +
    geom_boxplot() +
    scale_y_log10(labels = dollar_format()) +
    coord_flip() +
    # wow, it is possible to use facets after ggplot call
    facet_wrap(~ distributor)
```

28:00 Biggest payoff (worldwide_gross/production_budget)

```{r}
# boxplot
movie_profit %>% 
    mutate(profit_ratio = worldwide_gross / production_budget) %>% 
    ggplot(aes(genre, profit_ratio)) +
    geom_boxplot() +
    scale_y_log10() +
    coord_flip()

# boxplots display over several orders of magnitude
movie_profit %>% 
    mutate(profit_ratio = worldwide_gross / production_budget) %>% 
    ggplot(aes(genre, profit_ratio)) +
    geom_boxplot() +
    scale_y_log10(
```






