```{r}
library(malariaAtlas)
library(tidyverse)
library(scales)
library(fuzzyjoin)
library(gganimate)
library(countrycode)
theme_set(theme_classic())

# get parasite rate
kenya_pr <- tibble::as_tibble((malariaAtlas::getPR(ISO = "KEN", species = "BOTH"))) %>% 
    filter(!is.na(pr))

# 25:45
malaria_inc <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-13/malaria_inc.csv")
malaria_deaths <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-13/malaria_deaths.csv")

# 27:00
malaria_in_process <- malaria_inc %>% 
    setNames(c("country", "code", "year", "incidence")) %>% 
    mutate(incidence = incidence / 1000)

malaria_deaths_processed <- malaria_deaths %>% 
    setNames(c("country", "code", "year", "deaths"))

malaria_spread <- malaria_in_process %>%  
    filter(year %in% c(2005, 2010, 2015)) %>% 
    mutate(year = paste0("Y", year)) %>% 
    filter(country != "Turkey",
           !is.na(code)) %>% 
    spread(year, incidence)

world <- map_data("world") %>% 
    filter(region != "Antarctica")

malaria_country_data <- malaria_deaths_processed %>% 
    # filter(year %% 10 == 0 & year == 2000) %>% 
    inner_join(maps::iso3166 %>% 
                   # do we keep only mapname here
                   select(a3, mapname), by = c(code = "a3")) %>% 
    mutate(mapname = str_remove(mapname, "\\(.*"))

malaria_map_data <- map_data("world") %>% 
    filter(region != "Antarctica") %>% 
    tbl_df() %>% 
    inner_join(malaria_country_data, by = c(region = "mapname")) %>% 
    filter(year %in% c(2000, 2005, 2010))
```

```{r}
kenya_pr %>% 
    group_by(year_start) %>% 
    summarise(examind = sum(examined),
              positiv = sum(positive),
              studies = n()) %>% 
    mutate(proportion = pstv / examnd) %>% 
    ggplot(aes(year_start, proportion)) +
    geom_line()
```

```{r}
# ggplot2::map_data("world") %>% tibble() %>% filter(region == "Kenya")
kenya_pr %>% 
    # %/% truncates the last digit  
    mutate(decade_alter = 10 * (year_start %/% 10)) %>% 
    # niiiice! This will show the highest pr´s on top of the graph
    # this will arrange from lowest to highest and plot highest last
    arrange(pr) %>% 
    ggplot(aes(longitude, latitude, colour = pr)) +
    geom_point() +
    borders("world", regions = "Kenya") +
    scale_color_gradient2(low = "blue", 
                          high = "red", 
                          midpoint = .5,
                          labels = percent_format()) +
    facet_wrap(~ decade_alter) +
    theme_void() +
    coord_map() +
    # changes the name of the legend
    labs(color = "Prevalence")
```

Aggregated across countries

# 28:00

```{r}
malaria_in_process %>% 
    # grabbing 6 unique countries
    # filter(country %in% sample(unique(country), 6)) %>%
    filter(country %in%  sample(unique(country), 6)) %>% 
    ggplot(aes(year, incidence, color = country)) +
    geom_line() +
    scale_y_continuous(labels = scales::percent_format())

malaria_deaths_processed %>% 
    # grabbing 6 unique countries
    # filter(country %in% sample(unique(country), 6)) %>%
    filter(country %in%  sample(unique(country), 6)) %>% 
    ggplot(aes(year, deaths, color = country)) +
    geom_line()
```


31:00: Blunt-Altman plot

```{r}
malaria_spread %>%
    mutate(current = Y2016,
           change = Y2016 - Y2000) %>% 
    ggplot(aes(current, change)) +
    geom_point() +
    geom_text(aes(label = code), vjust = 1, hjust = 1)
```

35:00

```{r}
malaria_in_process %>% 
    filter(incidence < 1) %>% 
    filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
    inner_join(maps::iso3166 %>% 
                   # do we keep only mapname here
                   select(a3, mapname), by = c(code = "a3")) %>% 
    # this will keep all regions
    # keeps all observations in y
    # right_join(world, by = c(mapname = "region")) %>% 
    # only what we have in malaria_spread, not the entire world in right_join
    inner_join(world, by = c(mapname = "region")) %>% 
    ggplot(aes(long, lat, group = group, fill = incidence)) +
    geom_polygon() +
    scale_fill_gradient2(low = "blue", 
                          high = "red", 
                          midpoint = .20,
                          labels = percent_format()) +
    coord_map() +
    facet_wrap(~ year) +
    theme_void()
```

```{r}
# WHERE IS MY R MOJO!!!
```

45:00 Malaria deaths over time

```{r}
# get parasite rate
kenya_pr <- tibble::as_tibble((malariaAtlas::getPR(ISO = "KEN", species = "BOTH"))) %>% 
    filter(!is.na(pr))


# 27:00
malaria_in_process <- malaria_inc %>% 
    setNames(c("country", "code", "year", "incidence")) %>% 
    mutate(incidence = incidence / 1000)

malaria_spread <- malaria_in_process %>%  
    filter(year %in% c(2005, 2010, 2015)) %>% 
    mutate(year = paste0("Y", year)) %>% 
    filter(country != "Turkey",
           !is.na(code)) %>% 
    spread(year, incidence)

world <- map_data("world") %>% 
    filter(region != "Antarctica")
```

48:00

```{r}

# this will keep all regions
# keeps all observations in y
# right_join(world, by = c(mapname = "region")) %>% 
# only what we have in malaria_spread, not the entire world in right_join
map_data("world") %>% 
    filter(region != "Antarctica") %>% 
    tbl_df() %>% 
    inner_join(malaria_country_data, by = c(region = "mapname")) %>% 
    ggplot(aes(long, lat, group = group, fill = deaths)) +
    geom_polygon() +
    scale_fill_gradient2(low = "blue", 
                         high = "red", 
                         midpoint = 100) +
    theme_void()
```

```{r}
malaria_map_data %>%  
    mutate(continent = countrycode(code, "iso3c", "continent")) %>% 
    filter(continent == "Africa") %>% 
    # every second year
    ggplot(aes(long, lat, group = group, fill = deaths)) +
    geom_polygon() +
    scale_fill_gradient2(low = "blue", 
                         high = "red", 
                         midpoint = 100) +
    theme_void() +
    labs(title = "Malaria deaths over time in the world",
         fill = "Deaths per 100 000") +
    transition_manual(year)
```

