```{r}
library(tidyverse)
library(scales)
library(broom)
library(splines)

theme_set(theme_light())

maryland_bridges <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2018/2018-11-27/baltimore_bridges.csv")

maryland_bridges <- maryland_bridges %>% 
    filter(yr_built >= 1900) %>% 
    mutate(inspection_yr = inspection_yr + 2000,
           decade = 10 * (yr_built %/% 10),
           responsibility = fct_lump(responsibility, 4),#
           county = str_to_title(county)) %>% 
    replace_na(list(responsibility = "Other")) 
```

09:00

```{r}
maryland_bridges %>% 
    count(decade = 10 * (yr_built %/% 10), sort = TRUE) %>% 
    ggplot(aes(decade, n)) +
    geom_line() +
    expand_limits(y = 0) +
    labs(y = "Number of bridges per decade")
```

11:00 How did condition of the bridges changed over time

```{r}
maryland_bridges %>% 
    group_by(decade) %>% 
    summarise(pct_good = mean(bridge_condition == "Good"),
              total = n()) %>% 
    ggplot(aes(decade, pct_good)) +
    geom_line() +
    geom_smooth(method = "lm") +
    scale_y_continuous(labels = percent_format()) +
    expand_limits(y = 0)
```

20:00

```{r}
maryland_bridges %>% 
    replace_na(list(responsibility = "Other")) %>% 
    count(responsibility = fct_lump(responsibility, 4), sort = TRUE) %>% 
    mutate(responsibility = fct_reorder(responsibility, n)) %>% 
    ggplot(aes(responsibility, n)) +
    geom_col() +
    coord_flip()
```

22:00

```{r}
maryland_bridges %>% 
    group_by(responsibility, decade)  %>%
    summarise(pct_good = mean(bridge_condition == "Good"),
              total = n()) %>% 
    filter(responsibility != "Other") %>% 
    ggplot(aes(decade, pct_good, color = responsibility)) +
    geom_line() +
    scale_y_continuous(labels = percent_format()) +
    expand_limits(y = 0) +
    labs(y = "% of bridges rated Good")
```

29:00

```{r}
maryland_bridges %>% 
    ggplot(aes(avg_daily_traffic)) +
    geom_histogram() +
    scale_x_log10(labels = comma_format())
```

30:00 Crazy cut function!

```{r}
maryland_bridges %>% 
    group_by(traffic_category = cut(avg_daily_traffic, c(0, 1000, 10000, Inf),
                                    labels = c("<1000", "1000 - 10.000", "10.000+"))) %>% 
    summarise(pct_good = mean(bridge_condition == "Good"),
              total = n())
```

34:00

```{r}
maryland_bridges %>% 
    ggplot(aes(long, lat, color = responsibility)) +
    borders("state", regions = "Maryland") +
    geom_point(size = 0.5) +
    coord_map() +
    theme_void()
```

38:00

```{r}
maryland_bridges %>% 
    ggplot(aes(long, lat, color = avg_daily_traffic)) +
    borders("state", regions = "Maryland") +
    geom_point() +
    scale_color_gradient2(low = "blue",
                          high = "red",
                          midpoint = log10(median(maryland_bridges$avg_daily_traffic)),
                          trans = "log10",
                          labels = comma_format()) +
    coord_map() +
    theme_void()
```

45:00

```{r}
maryland_bridges %>% 
    group_by(county, decade)  %>%
    summarise(pct_good = mean(bridge_condition == "Good"),
              total = n()) %>% 
    arrange(county, decade) %>% 
    ggplot(aes(decade, pct_good, color = county)) +
    geom_line() +
    scale_y_continuous(labels = percent_format()) +
    expand_limits(y = 0) +
    labs(y = "% of bridges rated Good")
```

48:00

```{r}
# linear model is bad here!
# bridge condition in not linear over time at oll
# need a logistic model!!!!!!!!!!!
# will fit a sigmoidal curve, shape is always the same!
model <- maryland_bridges %>% 
    mutate(good = bridge_condition == "Good") %>% 
    glm(good ~ ns(yr_built, 4) + responsibility + county, data = ., family = "binomial")
```

51:00

```{r}
augment(model, maryland_bridges, type.predict = "response") %>% 
    ggplot(aes(yr_built, .fitted, color = responsibility)) +
    geom_line() +
    expand_limits(y = 0) +
    facet_wrap(~ county) +
    scale_y_continuous(labels = percent_format()) +
    labs(y = "Predicted probability of a bridge being GOOD")
```

1:02:00

```{r}
# coefficient plot
model %>% 
    tidy() %>% 
    filter(str_detect(term, "responsibility|county")) %>% 
    mutate(term = fct_reorder(term, estimate)) %>% 
    ggplot(aes(estimate, term)) +
    geom_point() +
    geom_vline(xintercept = 0, color = "red", lty = 2)
```

