```{r}
library(tidyverse)
library(mapproj)
library(gganimate)

us_wind <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-06/us_wind.csv")


us_wind <- us_wind %>% 
    filter(!t_state %in% c("AK", "HI", "GU", "PR")) %>% 
    # this is so ugly but very effective
    # would like to know if this is possible in python in one line
    mutate(t_cap = ifelse(t_cap < 0, NA, t_cap)) %>% 
    mutate_if(is.numeric, ~ ifelse(. == -9999, NA, .))




# to use the color aesthetic and see the 6 lumped categories we need some magic!
wind_projects <- us_wind %>% 
    group_by(p_name, t_state) %>% 
    # we should rename the variable to use it second time inside the function!!!
    summarise(year = min(p_year, na.rm = TRUE),
              # decided to keep missing data (it is an active decision)
              total_capacity = sum(t_cap),
              turbines = n(),
              lon = mean(xlong),
              lat = mean(ylat),
              lon_sd = sd(xlong),
              lat_sd = sd(ylat))
```

Starting most of the time with counts of categorical columns

Looking only a continental US plus Disctrict of Columbia (Washington) 


```{r}

us_wind %>% 
    # FALSE comes before TRUE (in this case Other is on top)
    # fct_lumped data needs to be arranged so that TRUE comes on the top of the table
    mutate(p_name = fct_lump(p_name, 6)) %>% 
    arrange(p_name != "Other") %>% 
    filter(xlong < 100) %>% 
    ggplot(aes(xlong, ylat, color = p_name)) +
    borders("state") +
    geom_point() + 
    coord_map() +
    theme_void()
```

```{r}
# one dot for every individual project
# in da HOUSE!
wind_projects %>% 
    ggplot(aes(lon, lat, size = turbines, color = year)) +
    borders("state") +
    geom_point() + 
    coord_map() +
    theme_void()
```

19:00

```{r}
us_wind %>% 
    distinct(p_name, p_year) %>% 
    count(p_name,sort = TRUE)

wind_projects %>% 
    ggplot(aes(year)) +
    geom_histogram()
```

26:00 How did total capacity changed over time?

```{r}
wind_projects %>% 
    group_by(year) %>% 
    ggplot(aes(year, total_capacity)) +
    geom_point()

wind_projects %>% 
    group_by(year) %>% 
    # if all of the capacity is divided under all turbines
    # you get the capacity for one turbine
    # how this changed over time
    ggplot(aes(year, total_capacity / turbines)) +
    geom_point()

wind_projects %>% 
    group_by(year) %>%
    # does not make sense
    ggplot(aes(year, turbines / total_capacity)) +
    geom_point()
```

39:00

```{r}
turbine_models <- us_wind %>% 
    group_by(t_model) %>% 
    # good for doing the same on many columns
    summarise(t_cap = median(t_cap),
              t_hh = median(t_hh), 
              t_rd = median(t_rd), 
              t_rsa = median(t_rsa), 
              t_ttlh = median(t_ttlh), 
              turbines = n(),
              projects = n_distinct(p_name)) %>% 
    arrange(desc(projects))

turbine_models %>% 
    ggplot(aes(t_rsa, t_cap)) +
    geom_point() +
    labs(title = "Bigger turbines is better in terms of efficiency")
```

47:00 Animation

```{r}

# No renderer backend detected. gganimate will default to writing frames to separate files
Consider installing:
ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  # Here comes the gganimate code
  transition_states(
    gear,
    transition_length = 2,
    state_length = 1
  ) +
  enter_fade() + 
  exit_shrink() +
  ease_aes('sine-in-out')

# one dot for every individual project
# in da HOUSE!
wind_projects %>% 
    ggplot(aes(lon, lat, size = turbines, color = year)) +
    borders("state") +
    geom_point() + 
    transition_states(
        year,
        transition_length = 2,
        state_length = 1
    ) +
    coord_map() +
    theme_void()
```

```{r}
wind_projects %>% 
    filter(!is.na(year), !is.infinite(year)) %>% 
    crossing(time = 1980:2017)
```

